"""Add date column to StudySchedule

Revision ID: 4ae7c7410d5c
Revises: b1ee675d7fe8
Create Date: 2024-10-29 19:07:17.702827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae7c7410d5c'
down_revision = 'b1ee675d7fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_schedule', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
