"""Change day_of_week col size.

Revision ID: a07726c8a92a
Revises: d7db5741f5b1
Create Date: 2024-10-30 22:26:33.416274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a07726c8a92a'
down_revision = 'd7db5741f5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_schedule', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_schedule', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
