"""Add week_type and course_type tables with references in StudySchedule

Revision ID: b1ee675d7fe8
Revises: 4c5ae072b695
Create Date: 2024-10-29 18:34:40.285293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ee675d7fe8'
down_revision = '4c5ae072b695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('week_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('instructor_name', sa.String(length=100), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('week_type_id', sa.Integer(), nullable=True),
    sa.Column('course_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_type_id'], ['course_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['week_type_id'], ['week_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_hours')
    op.drop_table('study_schedule')
    op.drop_table('week_type')
    op.drop_table('course_type')
    # ### end Alembic commands ###
