"""Remove nullable to end_time work.

Revision ID: d7db5741f5b1
Revises: c0b80f5c3a44
Create Date: 2024-10-30 14:48:55.808598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7db5741f5b1'
down_revision = 'c0b80f5c3a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_hours', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_hours', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
