name: Deploy Flask App

on:
  push:
    branches: ["master"]

jobs:
  deploy-client:
    runs-on: self-hosted

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        cd /var/www/hour-reporter
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Restart application
      run: |
        sudo systemctl restart hour-reporter.service
